import { ServicoData } from "./ModalServico";

export const servicosData: ServicoData[] = [
  {
    id: "nacionalidade",
    titulo: "Nacionalidade",
    icon: "/Icons/Servicos/Nacionalidade.png",
    altText: "Ícone de Nacionalidade",
    topicos: [
      "Assessoria completa para obtenção de nacionalidade brasileira, portuguesa e europeia.",
      "Avaliação profissional da viabilidade do pedido de cidadania.",
      "Representação em cartórios para obtenção de certidões e documentos.",
      "Consultoria para organização de documentos, traduções e legalizações.",
      "Condução do processo de nacionalidade junto aos órgãos competentes.",
      "Cidadania portuguesa permite viver na UE e viajar sem visto para diversos países.",
      "Cidadania brasileira oferece isenção de visto para +146 países e acesso ao mercado de trabalho.",
      "Atendimento personalizado para orientar e acompanhar todo o processo de naturalização.",
    ],
  },
  {
    id: "imigracao",
    titulo: "Imigração",
    icon: "/Icons/Servicos/Imigracao.png",
    altText: "Ícone de Imigração",
    topicos: [
      "Assessoria completa em processos de visto e autorização de residência.",
      "Orientação sobre os tipos de visto mais adequados ao seu perfil.",
      "Acompanhamento em todas as etapas do processo migratório.",
      "Representação junto às entidades competentes (SEF/AIMA).",
      "Apoio na reunificação familiar e reagrupamento.",
      "Consultoria para renovação e alteração de títulos de residência.",
      "Orientação sobre direitos e deveres dos imigrantes em Portugal.",
    ],
  },
  {
    id: "sentenca",
    titulo: "Sentença Estrangeira",
    icon: "/Icons/Servicos/Sentenca.png",
    altText: "Ícone de Sentença Estrangeira",
    topicos: [
      "Homologação de sentenças estrangeiras para produção de efeitos em Portugal.",
      "Reconhecimento de decisões judiciais de divórcio, guarda e partilha.",
      "Assessoria em processos de revisão e confirmação de sentenças.",
      "Apoio na tradução e legalização de documentos judiciais.",
      "Representação junto aos tribunais competentes.",
      "Orientação sobre convenções internacionais aplicáveis.",
    ],
  },
  {
    id: "familia",
    titulo: "Família e Sucessões",
    icon: "/Icons/Servicos/Familia.png",
    altText: "Ícone de Família e Sucessões",
    topicos: [
      "Assessoria em processos de divórcio, separação e regulação de responsabilidades parentais.",
      "Consultoria em questões de herança e partilha de bens.",
      "Apoio em inventários e processos sucessórios.",
      "Orientação sobre regime de bens e contratos pré-nupciais.",
      "Representação em processos de adoção e tutela.",
      "Consultoria em direito de família internacional.",
    ],
  },
  {
    id: "imoveis",
    titulo: "Imóveis",
    icon: "/Icons/Servicos/Imoveis.png",
    altText: "Ícone de Imóveis",
    topicos: [
      "Assessoria na compra e venda de imóveis em Portugal.",
      "Análise e elaboração de contratos de arrendamento.",
      "Due diligence imobiliária completa.",
      "Apoio em financiamentos e crédito habitação.",
      "Orientação sobre impostos e taxas na aquisição de imóveis.",
      "Representação em processos de despejo e litígios imobiliários.",
    ],
  },
  {
    id: "empresas",
    titulo: "Empresas",
    icon: "/Icons/Servicos/Empresas.png",
    altText: "Ícone de Empresas",
    topicos: [
      "Constituição e registro de empresas em Portugal.",
      "Assessoria em contratos comerciais e societários.",
      "Consultoria em fusões, aquisições e reestruturações.",
      "Apoio em questões de propriedade intelectual.",
      "Orientação sobre regime fiscal e tributário.",
      "Representação em processos de insolvência e recuperação empresarial.",
    ],
  },
];
